blog/urls.py
from django.urls import path
from blog import views

app_name = "user"

urlpatterns = [
    path("", views.main, name="main"),
    path("detail", views.detail, name="detail"),
    path("cover", views.cover, name="cover"),
    path("recommend", views.recommend, name="recommend"),
    path("result", views.result, name="result"),
    path("about", views.about, name="about"),
    path("signup", views.signup, name="signup"),
    path("login", views.login_view, name="login"),
    path("coin", views.coin, name="coin"),
    path("btc", views.btc, name="btc"),
    path("ada", views.ada, name="ada"),
    path("doge", views.doge, name="doge"),
    path("omg", views.omg, name="omg"),
    path("bch", views.bch, name="bch"),
    path("eos", views.eos, name="eos"),
    path("snt", views.snt, name="snt"),
    path("eth", views.eth, name="eth"),
    path("xrp", views.xrp, name="xrp"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", RedirectView.as_view(url="/blog/", permanent=True)),
    path("detail/", include("blog.urls")),
    path("recommend/", include("blog.urls")),
    path("about/", include("blog.urls")),
    path("cover/", include("blog.urls")),
    path("result/", include("blog.urls")),
    path("signup/", include("blog.urls")),
    path("login/", include("blog.urls")),
    path("coin/", include("blog.urls")),
    path("btc/", include("blog.urls")),
    path("ada/", include("blog.urls")),
    path("doge/", include("blog.urls")),
    path("omg/", include("blog.urls")),
    path("bch/", include("blog.urls")),
    path("eos/", include("blog.urls")),
    path("snt/", include("blog.urls")),
    path("eth/", include("blog.urls")),
    path("xrp/", include("blog.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as AbstractUserManager

# Create your models here.
class UserManager(AbstractUserManager):
    pass

class User(AbstractUser):
    objects = UserManager()

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from datetime import datetime, timedelta
from .final import input_n_bounds_alevel_output_crypto, Recommendation_DB
from .models import User
from django.contrib.auth.decorators import login_required

# Create your views here.


def main(request):
    data = {
            }

    return render(request, "Main.html", data)


def cover(request):
    context = {

    }

    return render(request, "Cover.html", context=context)


@login_required(login_url='/blog/login')
def detail(request):
    context = {

    }

    return render(request, "More-in-crypto.html", context=context)


@login_required(login_url='/blog/login')
def recommend(request):
    context = {

    }

    return render(request, "Recommendation.html", context=context)


modeling={}


def result(request):
    if request.method == "POST":
        select = request.POST.getlist('select')
        data = {'select': select}
        print(data["select"][0:4])
        global modeling
        modeling = {
            'model': input_n_bounds_alevel_output_crypto(int(data["select"][2]), int(data["select"][3]), int(data["select"][0]), int(data["select"][1]))
        }
        print(modeling)
    return render(request, "Result.html", modeling)


def about(request):
    context = {

    }

    return render(request, "About.html", context=context)


def signup(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        phonenumber = request.POST["phonenumber"]

        user = User.objects.create_user(username, email, password)
        user.phonenumber = phonenumber
        user.save()
        return redirect("user:login")

    return render(request, "Signup.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증 성공")
            login(request, user)
            return redirect("user:main")
        else:
            return render(request, "login.html", {
                'error': '비밀번호가 틀립니다.'
            })
            print("인증 실패")
    return render(request, "login.html")


def coin(request):
    if modeling["model"][0] == 'BTC':
        return render(request, "BTC.html")
    elif modeling["model"][0] == 'ADA':
        return render(request, "ADA.html")
    elif modeling["model"][0] == 'DOGE':
        return render(request, "DOGE.html")
    elif modeling["model"][0] == 'OMG':
        return render(request, "OMG.html")
    elif modeling["model"][0] == 'BCH':
        return render(request, "BCH.html")
    elif modeling["model"][0] == 'EOS':
        return render(request, "EOS.html")
    elif modeling["model"][0] == 'SNT':
        return render(request, "SNT.html")
    elif modeling["model"][0] == 'ETH':
        return render(request, "ETH.html")
    else:
        return render(request, "XRP.html")
    return render(request, "Main.html", context=context)


def btc(request):
    context = {

    }

    return render(request, "BTC.html", context=context)


def ada(request):
    context = {

    }

    return render(request, "ADA.html", context=context)


def doge(request):
    context = {

    }

    return render(request, "DOGE.html", context=context)


def omg(request):
    context = {

    }

    return render(request, "OMG.html", context=context)


def bch(request):
    context = {

    }

    return render(request, "BCH.html", context=context)


def eos(request):
    context = {

    }

    return render(request, "EOS.html", context=context)


def snt(request):
    context = {

    }

    return render(request, "SNT.html", context=context)


def eth(request):
    context = {

    }

    return render(request, "ETH.html", context=context)


def xrp(request):
    context = {

    }

    return render(request, "XRP.html", context=context)

blog/templates/ADA.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    {% load static %}
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
    $(document).ready( function() {
    $("#ADA").load("{% static 'html/ADA.html' %}");
    });
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Cryptocurren​cy&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Sentiment&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Index">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>coin_ADA</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/Each.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 4.0.3, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    
    
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="coin_BTC">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body"><header class="u-clearfix u-custom-color-1 u-header u-header" id="sec-3ee1"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
            <a class="u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;"><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</symbol>
</defs></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-spacing-30 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:main' %}" style="padding: 10px 0px;">Main</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:detail' %}" style="padding: 10px 0px;">More in crypto</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:recommend' %}" style="padding: 10px 0px;">Recommendation</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:about' %}" style="padding: 10px 0px;">About</a>
</li>{% if user.is_active %}<li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:login' %}" style="padding: 10px 0px;">Logout</a>
</li>{% else %}<li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:login' %}" style="padding: 10px 0px;">Login</a>
</li>{% endif %}</ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:main' %}" style="padding: 10px 0px;">Main</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:detail' %}" style="padding: 10px 0px;">More in crypto</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:recommend' %}" style="padding: 10px 0px;">Recommendation</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:about' %}" style="padding: 10px 0px;">About</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div></header>
    <section class="u-clearfix u-custom-color-1 u-section-1" id="sec-6191">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-align-left u-custom-font u-font-playfair-display u-text u-text-body-alt-color u-text-1" data-animation-name="fadeIn" data-animation-duration="1500" data-animation-direction="Down">Cryptocurren​cy<br>&nbsp;Sentiment Data<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Solution
        </h1>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-white u-section-2" id="carousel_d186">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h3 class="u-text u-text-1">&lt; ADA &gt;</h3>
        <div class="u-border-3 u-border-grey-dark-1 u-line u-line-horizontal u-line-1"></div>
      </div>
    </section>
    <section class="u-clearfix u-section-3" id="sec-9098">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-align-left u-container-style u-expanded-width u-grey-5 u-group u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <div id="ADA"></div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-white u-section-4" id="sec-aa58">
      <div class="u-align-left u-clearfix u-sheet u-sheet-1">
        <a href="{% url 'user:detail' %}" data-page-id="60132879" class="u-btn u-button-style u-none u-text-body-color u-text-hover-palette-2-base u-btn-1">
          <br>&nbsp;More in crypto&nbsp;<span class="u-icon u-icon-1"><svg class="u-svg-content" viewBox="0 -32 426.66667 426" style="width: 1em; height: 1em;"><path d="m213.332031 181.667969c0 4.265625-1.277343 8.53125-3.625 11.730469l-106.667969 160c-3.839843 5.761718-10.238281 9.601562-17.707031 9.601562h-64c-11.730469 0-21.332031-9.601562-21.332031-21.332031 0-4.269531 1.28125-8.535157 3.625-11.734375l98.773438-148.265625-98.773438-148.269531c-2.34375-3.199219-3.625-7.464844-3.625-11.730469 0-11.734375 9.601562-21.335938 21.332031-21.335938h64c7.46875 0 13.867188 3.839844 17.707031 9.601563l106.667969 160c2.347657 3.199218 3.625 7.464844 3.625 11.734375zm0 0"></path><path d="m426.667969 181.667969c0 4.265625-1.28125 8.53125-3.628907 11.730469l-106.664062 160c-3.839844 5.761718-10.242188 9.601562-17.707031 9.601562h-64c-11.734375 0-21.335938-9.601562-21.335938-21.332031 0-4.269531 1.28125-8.535157 3.628907-11.734375l98.773437-148.265625-98.773437-148.269531c-2.347657-3.199219-3.628907-7.464844-3.628907-11.730469 0-11.734375 9.601563-21.335938 21.335938-21.335938h64c7.464843 0 13.867187 3.839844 17.707031 9.601563l106.664062 160c2.347657 3.199218 3.628907 7.464844 3.628907 11.734375zm0 0"></path></svg><img></span>
        </a>
      </div>
    </section>
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-408c"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">2조 떡상하조<br>DS 김승연 천준&nbsp;<br>DE 김태완 박현주 이강혁 이학준
        </p>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/website-templates" target="_blank">
        <span>Website Templates</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="" target="_blank">
        <span>Website Builder Software</span>
      </a>. 
    </section>
  </body>
</html>

blog/templates/login.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="design, Premium DesignAmazing PhotoCreative IdeasUnique Strategy, Art Director, Creative form in our design, New Illustration Style, Wild Style, Wildand Magical, design., Creative form in our design">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>login</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 4.0.3, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="login">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body u-overlap u-white"><header class="u-clearfix u-custom-color-1 u-header u-header" id="sec-3ee1"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
            <a class="u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;"><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</symbol>
</defs></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-spacing-30 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="Main.html" style="padding: 10px 0px;">Main</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:detail' %}" style="padding: 10px 0px;">More in crypto</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:recommend' %}" style="padding: 10px 0px;">Recommendation</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:about' %}" style="padding: 10px 0px;">About</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-grey-90 u-border-hover-grey-50 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-hover-grey-90 u-text-white" href="{% url 'user:login' %}" style="padding: 10px 0px;">Login</a>
</li></ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:main' %}" style="padding: 10px 0px;">Main</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:detail' %}" style="padding: 10px 0px;">More in crypto</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:recommend' %}" style="padding: 10px 0px;">Recommendation</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'user:about' %}" style="padding: 10px 0px;">About</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div></header>
    <section class="u-clearfix u-custom-color-1 u-section-1" id="sec-a353">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-align-center u-custom-font u-font-playfair-display u-text u-text-body-alt-color u-text-1"> Cryptocurren​cy<br>&nbsp;Sentiment Data<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Solution
        </h1>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-section-2" id="carousel_a722">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-form u-login-control u-form-1">
          <form action="#" method="POST" class="u-clearfix u-form-custom-backend u-form-spacing-10 u-form-vertical u-inner-form" source="custom" name="form" style="padding: 10px;">{% csrf_token %}
            <div class="u-form-group u-form-name">
              <label for="username-a30d" class="u-label">ID</label>
              <input type="text" placeholder="Enter your ID" id="username-a30d" name="username" class="u-border-grey-30 u-input u-input-rectangle u-input-1" required="">
            </div>
            <div class="u-form-group u-form-password">
              <label for="password-a30d" class="u-label">Password</label>
              <input type="password" placeholder="Enter your Password" id="password-a30d" name="password" class="u-border-grey-30 u-input u-input-rectangle u-input-2" required="">
            </div>
            <div class="u-form-checkbox u-form-group">
              <input type="checkbox" id="checkbox-a30d" name="remember" value="On">
              <label for="checkbox-a30d" class="u-label">Remember me</label>
            </div>
            <div class="u-align-left u-form-group u-form-submit">
              <a href="#" class="u-border-none u-btn u-btn-submit u-button-style u-custom-color-1 u-hover-grey-40 u-btn-1">Login</a>
              <input type="submit" value="submit" class="u-form-control-hidden">
            </div>
            <input type="hidden" value="" name="recaptchaResponse">
          </form>
        </div>
        <p class="u-text u-text-default u-text-1">
          <a class="u-active-none u-border-none u-btn u-button-link u-button-style u-hover-none u-none u-text-black u-btn-2" href="{% url 'user:signup' %}" data-page-id="82914253">Don't have an account?</a>
        </p>
      </div>
    </section>
    <style class="u-overlap-style">.u-overlap:not(.u-sticky-scroll) .u-header {
background-color: custom-color-1 !important
}</style>
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-408c"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">2조 떡상하조<br>DS 김승연 천준&nbsp;<br>DE 김태완 박현주 이강혁 이학준
        </p>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/website-design" target="_blank">
        <span>Website Design Ideas</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="" target="_blank">
        <span>Website Builder Software</span>
      </a>. 
    </section><span style="height: 64px; width: 64px; margin-left: 0px; margin-right: auto; margin-top: 0px; background-image: none; right: 15px; bottom: 35px;" class="u-back-to-top u-grey-40 u-icon u-icon-circle u-opacity u-opacity-85 u-spacing-20 u-text-white" data-href="#">
        <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 551.13 551.13"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-1d98"></use></svg>
        <svg class="u-svg-content" enable-background="new 0 0 551.13 551.13" viewBox="0 0 551.13 551.13" xmlns="http://www.w3.org/2000/svg" id="svg-1d98" data-color="rgb(71, 138, 201)"><path d="m275.565 189.451 223.897 223.897h51.668l-275.565-275.565-275.565 275.565h51.668z"></path></svg>
    </span>
  </body>
</html>